language: node_js
node_js: 
  - '8.5.0'
notifications:      # 每次构建的时候是否通知，如果不想收到通知邮箱（个人感觉邮件贼烦），那就设置 false 吧
  email: false
addons:
  chrome: stable
#before_script:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
# 执行install
install:
 - npm install
# 执行命令脚本
script:
 - npm run test